on:
    push:
      branches: [ "main" ]

env:
    BUILD_TYPE: Release

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3

            - name: CMake Configure
              run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            
            - name: CMake Build
              run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

            - name: Build Executable
              uses: actions/upload-artifact@v3
              with:
                name: Incalescent.exe
                path: ${{github.workspace}}/build/Release/incalescent.exe
            
            - name: Build Executable (Sneaky)
              uses: actions/upload-artifact@v3
              with:
                name: Incalescent.exe.txt
                path: ${{github.workspace}}/build/Release/incalescent.exe
